export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const DELETE_DATA_FROM_MONTHLY = "DELETE_DATA_FROM_MONTHLY";
export const UPDATE_MONTHLY_DATA = "UPDATE_MONTHLY_DATA";
export const UPDATE_LOADING = "UPDATE_LOADING";
export const UPDATE_YEARLY_DATA = "UPDATE_YEARLY_DATA";
export const UPDATE_FORM_TITLE_LIST = "UPDATE_FORM_TITLE_LIST";
